### PR TITLE
Automatically refresh category when querying Card

### LINKED ISSUE #468: when reviewing a card the category does not show in the status line
When viewing a card for the first time, the category appears in the status line.  If I select again and when AnyMemo chooses it again, the category does not appear.  If I quit and restart the category appears.

### PR DESCRIPTION
**Pull request by gaul**
Fixes #468.

### CODE REVIEW

**Comment by gaul** [comment]
Accidentally deleted remote branch.

**Comment by helloworld1** [comment]
Emmm, not sure about the performance impact of this. Here is the doc: 

  | // the account field in Order has foreignAutoCreate=true Order order1 = new Order(); // account1 has not been created in the db yet, id field is null order1.account = account1; // this will create order1 in the order table _and_ // pass order1.account to the internal accountDao.create(). orderDao.create(order1);
-- | --


Also did it create a new category for each card?

**Comment by gaul** [comment]
@helloworld1 this code uses *foreignAutoRefresh*, not foreignAutoCreate:

http://ormlite.com/javadoc/ormlite-core/doc-files/ormlite_2.html#foreignAutoRefresh

This should only query the missing fields into memory, in this case the card category.

**Comment by gaul** [comment]
@helloworld1 rebased.

**Comment by helloworld1** [comment]
Personally I don't like auto refresh. We can try it out though.

**Pull request merged**
