### PR TITLE
Toast instead of notify during conversion

### PR DESCRIPTION
**Pull request by gaul**
Android docs recommend this since we only display simple feedback:

https://ux.stackexchange.com/questions/76288/android-toast-vs-alert-dialog

References #458.

### CODE REVIEW

**Comment by helloworld1** [comment]
I don't quite agree using Toast in this case since Notification can work when the app is in background. Also foreground notification will the conversion process less likely to be killed by the system when the app is in background.

**Comment by gaul** [comment]
These notifications are not actually displaying though.

**Comment by gaul** [comment]
Also, how long do we expect these conversions to take?  I observe at most a few seconds with thousands of cards.

**Comment by gaul** [comment]
Abandoning.

**Pull request closed without merging**
